/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedEntradasRouteImport } from './routes/_authenticated/entradas'
import { Route as AuthenticatedFolhaRouteImport } from './routes/_authenticated/folha'
import { Route as AuthenticatedMensalidadesRouteImport } from './routes/_authenticated/mensalidades'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntradasRoute = AuthenticatedEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFolhaRoute = AuthenticatedFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensalidadesRoute =
  AuthenticatedMensalidadesRouteImport.update({
    id: '/mensalidades',
    path: '/mensalidades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/entradas': typeof AuthenticatedEntradasRoute
  '/folha': typeof AuthenticatedFolhaRoute
  '/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/entradas': typeof AuthenticatedEntradasRoute
  '/folha': typeof AuthenticatedFolhaRoute
  '/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/painel': typeof AuthenticatedPainelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/entradas': typeof AuthenticatedEntradasRoute
  '/_authenticated/folha': typeof AuthenticatedFolhaRoute
  '/_authenticated/mensalidades': typeof AuthenticatedMensalidadesRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/despesas'
    | '/entradas'
    | '/folha'
    | '/mensalidades'
    | '/painel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/despesas'
    | '/entradas'
    | '/folha'
    | '/mensalidades'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/despesas'
    | '/_authenticated/entradas'
    | '/_authenticated/folha'
    | '/_authenticated/mensalidades'
    | '/_authenticated/painel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entradas': {
      id: '/_authenticated/entradas'
      path: '/entradas'
      fullPath: '/entradas'
      preLoaderRoute: typeof AuthenticatedEntradasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/folha': {
      id: '/_authenticated/folha'
      path: '/folha'
      fullPath: '/folha'
      preLoaderRoute: typeof AuthenticatedFolhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensalidades': {
      id: '/_authenticated/mensalidades'
      path: '/mensalidades'
      fullPath: '/mensalidades'
      preLoaderRoute: typeof AuthenticatedMensalidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedEntradasRoute: typeof AuthenticatedEntradasRoute
  AuthenticatedFolhaRoute: typeof AuthenticatedFolhaRoute
  AuthenticatedMensalidadesRoute: typeof AuthenticatedMensalidadesRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedEntradasRoute: AuthenticatedEntradasRoute,
  AuthenticatedFolhaRoute: AuthenticatedFolhaRoute,
  AuthenticatedMensalidadesRoute: AuthenticatedMensalidadesRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
